#!/bin/bash -e
#
# Debian Packaging Scripts
# Copyright (C) 2002-2016 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de

. ./debian.conf


CHANGELOG_HEADER="`head -n1 debian/changelog`"
PACKAGE=`echo $CHANGELOG_HEADER | sed -e "s/(.*//" -e "s/ //g"`
UPSTREAM_VERSION=`echo $CHANGELOG_HEADER | sed -e "s/[a-zA-Z0-9 \-]*(//" -e "s/).*//" -e "s/[0-9]*$//" -e "s/ //g" -e "s/^[0-9]*://" -e "s/-[^ ]*$//g"`

echo "######################################################################"
echo "CHANGELOG_HEADER:   $CHANGELOG_HEADER"
echo "PACKAGE:            $PACKAGE"
echo "UPSTREAM_VERSION:   $UPSTREAM_VERSION"
echo "######################################################################"

if [ -e $PACKAGE-$UPSTREAM_VERSION ] ; then
   rm -rf $PACKAGE-$UPSTREAM_VERSION
fi
mkdir $PACKAGE-$UPSTREAM_VERSION || exit 1


# ---------------------------------------------------------
mkdir $PACKAGE-$UPSTREAM_VERSION/src
cp README COPYING $PACKAGE-$UPSTREAM_VERSION
cp src/adnsmodule.c $PACKAGE-$UPSTREAM_VERSION
cp src/ADNS.py $PACKAGE-$UPSTREAM_VERSION
cp src/DNSBL.py $PACKAGE-$UPSTREAM_VERSION
cp src/MANIFEST.in $PACKAGE-$UPSTREAM_VERSION
cp src/setup.py $PACKAGE-$UPSTREAM_VERSION
cp src/test.py $PACKAGE-$UPSTREAM_VERSION
# ---------------------------------------------------------


tar czvf $PACKAGE-$UPSTREAM_VERSION.tar.gz $PACKAGE-$UPSTREAM_VERSION
rm -rf $PACKAGE-$UPSTREAM_VERSION
